# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_WrapLem', [dirname(__file__)])
        except ImportError:
            import _WrapLem
            return _WrapLem
        if fp is not None:
            try:
                _mod = imp.load_module('_WrapLem', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _WrapLem = swig_import_helper()
    del swig_import_helper
else:
    import _WrapLem
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class CascadeLemmatizer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CascadeLemmatizer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CascadeLemmatizer, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["assembleLemmatizer"] = lambda x: _WrapLem.CascadeLemmatizer_assembleLemmatizer
    if _newclass:
        assembleLemmatizer = staticmethod(_WrapLem.CascadeLemmatizer_assembleLemmatizer)
    __swig_getmethods__["toString"] = lambda x: _WrapLem.CascadeLemmatizer_toString
    if _newclass:
        toString = staticmethod(_WrapLem.CascadeLemmatizer_toString)
    __swig_getmethods__["toUnicode"] = lambda x: _WrapLem.CascadeLemmatizer_toUnicode
    if _newclass:
        toUnicode = staticmethod(_WrapLem.CascadeLemmatizer_toUnicode)

    def lemmatize(self, *args):
        return _WrapLem.CascadeLemmatizer_lemmatize(self, *args)

    def lemmatizeS(self, *args):
        return _WrapLem.CascadeLemmatizer_lemmatizeS(self, *args)
    __swig_destroy__ = _WrapLem.delete_CascadeLemmatizer
    __del__ = lambda self: None
CascadeLemmatizer_swigregister = _WrapLem.CascadeLemmatizer_swigregister
CascadeLemmatizer_swigregister(CascadeLemmatizer)
cvar = _WrapLem.cvar

def CascadeLemmatizer_assembleLemmatizer():
    return _WrapLem.CascadeLemmatizer_assembleLemmatizer()
CascadeLemmatizer_assembleLemmatizer = _WrapLem.CascadeLemmatizer_assembleLemmatizer

def CascadeLemmatizer_toString(arg2):
    return _WrapLem.CascadeLemmatizer_toString(arg2)
CascadeLemmatizer_toString = _WrapLem.CascadeLemmatizer_toString

def CascadeLemmatizer_toUnicode(arg2):
    return _WrapLem.CascadeLemmatizer_toUnicode(arg2)
CascadeLemmatizer_toUnicode = _WrapLem.CascadeLemmatizer_toUnicode

# This file is compatible with both classic and new-style classes.


