FIND_PATH(LOKI_INCLUDE_DIR loki/LokiExport.h /usr/include /usr/local/include)

FIND_LIBRARY(LOKI_LIBRARY NAMES loki PATHS /usr/lib /usr/local/lib) 

MARK_AS_ADVANCED(LOKI_LIBRARY)
MARK_AS_ADVANCED(LOKI_INCLUDE_DIR)


IF (LOKI_INCLUDE_DIR AND LOKI_LIBRARY)
   SET(LOKI_FOUND TRUE)
ENDIF (LOKI_INCLUDE_DIR AND LOKI_LIBRARY)


IF (LOKI_FOUND)
   IF (NOT LOKI_FIND_QUIETLY)
      MESSAGE(STATUS "Found LOKI: ${LOKI_LIBRARY}")
   ENDIF (NOT LOKI_FIND_QUIETLY)
ELSE (LOKI_FOUND)
   IF (Loki_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Loki-lib")
   ELSE (Loki_FIND_REQUIRED)
      MESSAGE(STATUS "Loki not found")
   ENDIF (Loki_FIND_REQUIRED)
ENDIF (LOKI_FOUND)
