/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CascadeLemmatizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CascadeLemmatizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CascadeLemmatizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LemJNI.delete_CascadeLemmatizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CascadeLemmatizer assembleLemmatizer() {
    return new CascadeLemmatizer(LemJNI.CascadeLemmatizer_assembleLemmatizer(), true);
  }

  public String lemmatize(String kwrd_orth, String kwrd_base, String kwrd_ctag, String kwrd_spaces, String category) {
    return LemJNI.CascadeLemmatizer_lemmatize__SWIG_0(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag, kwrd_spaces, category);
  }

  public String lemmatize(String kwrd_orth, String kwrd_base, String kwrd_ctag, String kwrd_spaces) {
    return LemJNI.CascadeLemmatizer_lemmatize__SWIG_1(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag, kwrd_spaces);
  }

  public String lemmatize(String kwrd_orth, String kwrd_base, String kwrd_ctag) {
    return LemJNI.CascadeLemmatizer_lemmatize__SWIG_2(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag);
  }

}
