/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package g419.polem;

public class WrapLemJNI {
  public final static native void globalMethod_set(String jarg1);
  public final static native String globalMethod_get();
  public final static native long CascadeLemmatizer_assembleLemmatizer__SWIG_0();
  public final static native long CascadeLemmatizer_assembleLemmatizer__SWIG_1(String jarg1);
  public final static native long CascadeLemmatizer_lemmatize__SWIG_0(long jarg1, CascadeLemmatizer jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, String jarg6, boolean jarg7);
  public final static native long CascadeLemmatizer_lemmatize__SWIG_1(long jarg1, CascadeLemmatizer jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, boolean jarg6);
  public final static native long CascadeLemmatizer_lemmatize__SWIG_2(long jarg1, CascadeLemmatizer jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);
  public final static native String CascadeLemmatizer_lemmatizeS__SWIG_0(long jarg1, CascadeLemmatizer jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native String CascadeLemmatizer_lemmatizeS__SWIG_1(long jarg1, CascadeLemmatizer jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native String CascadeLemmatizer_lemmatizeS__SWIG_2(long jarg1, CascadeLemmatizer jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void delete_CascadeLemmatizer(long jarg1);
}
