/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CascadeLemmatizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CascadeLemmatizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CascadeLemmatizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LemJNI.delete_CascadeLemmatizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CascadeLemmatizer assembleLemmatizer() {
    return new CascadeLemmatizer(LemJNI.CascadeLemmatizer_assembleLemmatizer(), true);
  }

  public static String toString(SWIGTYPE_p_UnicodeString in) {
    return LemJNI.CascadeLemmatizer_toString(SWIGTYPE_p_UnicodeString.getCPtr(in));
  }

  public static SWIGTYPE_p_UnicodeString toUnicode(String in) {
    return new SWIGTYPE_p_UnicodeString(LemJNI.CascadeLemmatizer_toUnicode(in), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag, SWIGTYPE_p_UnicodeString kwrd_spaces, String category) {
    return new SWIGTYPE_p_UnicodeString(LemJNI.CascadeLemmatizer_lemmatize__SWIG_0(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_spaces), category), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag, SWIGTYPE_p_UnicodeString kwrd_spaces) {
    return new SWIGTYPE_p_UnicodeString(LemJNI.CascadeLemmatizer_lemmatize__SWIG_1(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_spaces)), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag) {
    return new SWIGTYPE_p_UnicodeString(LemJNI.CascadeLemmatizer_lemmatize__SWIG_2(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag)), true);
  }

}
