/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CascadeLemmatizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CascadeLemmatizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CascadeLemmatizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WrapLemJNI.delete_CascadeLemmatizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CascadeLemmatizer assembleLemmatizer() {
    return new CascadeLemmatizer(WrapLemJNI.CascadeLemmatizer_assembleLemmatizer__SWIG_0(), true);
  }

  public static CascadeLemmatizer assembleLemmatizer(String datafiles) {
    return new CascadeLemmatizer(WrapLemJNI.CascadeLemmatizer_assembleLemmatizer__SWIG_1(datafiles), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag, SWIGTYPE_p_UnicodeString kwrd_spaces, String category, boolean debug) {
    return new SWIGTYPE_p_UnicodeString(WrapLemJNI.CascadeLemmatizer_lemmatize__SWIG_0(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_spaces), category, debug), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag, SWIGTYPE_p_UnicodeString kwrd_spaces, boolean debug) {
    return new SWIGTYPE_p_UnicodeString(WrapLemJNI.CascadeLemmatizer_lemmatize__SWIG_1(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_spaces), debug), true);
  }

  public SWIGTYPE_p_UnicodeString lemmatize(SWIGTYPE_p_UnicodeString kwrd_orth, SWIGTYPE_p_UnicodeString kwrd_base, SWIGTYPE_p_UnicodeString kwrd_ctag, boolean debug) {
    return new SWIGTYPE_p_UnicodeString(WrapLemJNI.CascadeLemmatizer_lemmatize__SWIG_2(swigCPtr, this, SWIGTYPE_p_UnicodeString.getCPtr(kwrd_orth), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_base), SWIGTYPE_p_UnicodeString.getCPtr(kwrd_ctag), debug), true);
  }

  public String lemmatizeS(String kwrd_orth, String kwrd_base, String kwrd_ctag, String kwrd_spaces, String category) {
    return WrapLemJNI.CascadeLemmatizer_lemmatizeS__SWIG_0(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag, kwrd_spaces, category);
  }

  public String lemmatizeS(String kwrd_orth, String kwrd_base, String kwrd_ctag, String kwrd_spaces) {
    return WrapLemJNI.CascadeLemmatizer_lemmatizeS__SWIG_1(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag, kwrd_spaces);
  }

  public String lemmatizeS(String kwrd_orth, String kwrd_base, String kwrd_ctag) {
    return WrapLemJNI.CascadeLemmatizer_lemmatizeS__SWIG_2(swigCPtr, this, kwrd_orth, kwrd_base, kwrd_ctag);
  }

}
