#FIND_PATH(MORFEUSZ_INCLUDE_DIR morfeusz.h /usr/include /usr/local/include)
#MARK_AS_ADVANCED(MORFEUSZ_INCLUDE_DIR)

FIND_LIBRARY(MORFEUSZ_LIBRARY NAMES morfeusz PATH /usr/lib /usr/local/lib)
MARK_AS_ADVANCED(MORFEUSZ_LIBRARY)

#IF (MORFEUSZ_INCLUDE_DIR AND MORFEUSZ_LIBRARY)
IF (MORFEUSZ_LIBRARY)
   SET(MORFEUSZ_FOUND TRUE)
ENDIF (MORFEUSZ_LIBRARY)


IF (MORFEUSZ_FOUND)
   IF (NOT Morfeusz_FIND_QUIETLY)
      MESSAGE(STATUS "Found Morfeusz: ${MORFEUSZ_LIBRARY}")
   ENDIF (NOT Morfeusz_FIND_QUIETLY)
ELSE (MORFEUSZ_FOUND)
   IF (Morfeusz_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Morfeusz")
   ENDIF (Morfeusz_FIND_REQUIRED)
ENDIF (MORFEUSZ_FOUND)
